//
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
//
export const VIEW_PRODUCT = "VIEW_PRODUCT";
//
export const RESET_DETAIL_PRODUCT = "RESET_DETAIL_PRODUCT";
//
export const VIEW_SCROLL_PRODUCT = "VIEW_SCROLL_PRODUCT";
//
export const HOVER_IMAGE_EVENT_DP = "HOVER_IMAGE_EVENT_DP";
//
export const CHOOSE_SIZE_PRODUCT = "CHOOSE_SIZE_PRODUCT";
//
export const ASC_OR_DESC_NUMBER_PRODUCT = "ASC_OR_DESC_NUMBER_PRODUCT";
//
export const ADD_CART = "ADD_CART";
//
export const GET_ALL_CART = "GET_ALL_CART";
//
export const SHOW_MODAL_ADD_CART_CURRENT = "SHOW_MODAL_ADD_CART_CURRENT";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const SCROLL_TOP = "SCROLL_TOP";
//
export const OPEN_CATEGORY = "OPEN_CATEGORY";
//
export const DELETE_CART_BY_ID = "DELETE_CART_BY_ID";
//
export const VIEW_FAST_PRODUCT = "VIEW_FAST_PRODUCT";
//
export const OPEN_VIEW_FAST_PRODUCT = "OPEN_VIEW_FAST_PRODUCT";
//
export const UPDATE_CART = "UPDATE_CART";
//
export const UPDATE_CART_ISSET = "UPDATE_CART_ISSET";
//
export const GET_PRODUCT_TOP_SELL = "GET_PRODUCT_TOP_SELL";
//
export const GET_ALL_BRAND_PRODUCT = "GET_ALL_BRAND_PRODUCT";
//
export const GET_ALL_COLOR_PRODUCT = "GET_ALL_COLOR_PRODUCT";
//
export const GET_ALL_SIZE_PRODUCT = "GET_ALL_SIZE_PRODUCT";
//
export const FILTER_PRODUCT_BRAND = "FILTER_PRODUCT_BRAND";
//
export const FILTER_PRODUCT_COLOR = "FILTER_PRODUCT_COLOR";
//
export const FILTER_PRODUCT_SIZE = "FILTER_PRODUCT_SIZE";
//
export const FILTER_PRODUCT_PRICE = "FILTER_PRODUCT_PRICE";
//
export const LOAD_PRODUCT_PAGE_PRODUCT = "LOAD_PRODUCT_PAGE_PRODUCT";
//
export const LOAD_VIEW_FAST_PRODUCT = "LOAD_VIEW_FAST_PRODUCT";
//
export const OPEN_MODAL_LOGIN = "OPEN_MODAL_LOGIN";
//
export const OPEN_MODAL_REGISTER = "OPEN_MODAL_REGISTER";
//
export const GET_ALL_USERS = "GET_ALL_USERS";
//
export const CHECK_HAVE_LOGIN = "CHECK_HAVE_LOGIN";
//
export const SAVE_USER_LOGIN = "SAVE_USER_LOGIN";
//
export const LOGOUT_USER = "LOGOUT_USER";
//
export const ADD_USER = "ADD_USER";
//
export const SET_MODAL_DEFAULT = "SET_MODAL_DEFAULT";
//
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
//
